//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment : IEntity
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public int AttachmentTypeId { get; set; }
        public int Count { get; set; }
        public string Notes { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> IsResponse { get; set; }
    
        public virtual AttachmentType AttachmentType { get; set; }
        public virtual Document Document { get; set; }
    }
}
