//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department : IEntity
    {
        public Department()
        {
            this.Department1 = new HashSet<Department>();
            this.Document = new HashSet<Document>();
            this.Document1 = new HashSet<Document>();
            this.ReadOnlyDepartment = new HashSet<ReadOnlyDepartment>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int DepartmentTypeId { get; set; }
        public bool Active { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual ICollection<Department> Department1 { get; set; }
        public virtual Department Department2 { get; set; }
        public virtual DepartmentType DepartmentType { get; set; }
        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<Document> Document1 { get; set; }
        public virtual ICollection<ReadOnlyDepartment> ReadOnlyDepartment { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
