//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Services
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMSEntities : DbContext
    {
        public DMSEntities()
            : base("name=DMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DepartmentType> DepartmentType { get; set; }
        public DbSet<DirectionType> DirectionType { get; set; }
        public DbSet<DocumentHistory> DocumentHistory { get; set; }
        public DbSet<DocumentProcedure> DocumentProcedure { get; set; }
        public DbSet<DocumentStatus> DocumentStatus { get; set; }
        public DbSet<ImportanceLevel> ImportanceLevel { get; set; }
        public DbSet<Issue> Issue { get; set; }
        public DbSet<Nationality> Nationality { get; set; }
        public DbSet<Procedure> Procedure { get; set; }
        public DbSet<ProcedureStatus> ProcedureStatus { get; set; }
        public DbSet<Registry> Registry { get; set; }
        public DbSet<RelatedPerson> RelatedPerson { get; set; }
        public DbSet<RequiredProcedure> RequiredProcedure { get; set; }
        public DbSet<SecurityLevel> SecurityLevel { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<Notification> Notification { get; set; }
        public DbSet<NotificationType> NotificationType { get; set; }
        public DbSet<AttachmentType> AttachmentType { get; set; }
        public DbSet<DocumentStatusReason> DocumentStatusReason { get; set; }
        public DbSet<DocumentType> DocumentType { get; set; }
        public DbSet<SentDocument> SentDocument { get; set; }
        public DbSet<ReadOnlyDepartment> ReadOnlyDepartment { get; set; }
        public DbSet<ReadOnlyType> ReadOnlyType { get; set; }
        public DbSet<ReadOnlyUser> ReadOnlyUser { get; set; }
        public DbSet<Document> Document { get; set; }
        public DbSet<Attachment> Attachment { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Department> Department { get; set; }
    }
}
