//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentStatus : IEntity
    {
        public DocumentStatus()
        {
            this.DocumentHistory = new HashSet<DocumentHistory>();
            this.DocumentStatusReason = new HashSet<DocumentStatusReason>();
            this.SentDocument = new HashSet<SentDocument>();
            this.Document = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DocumentHistory> DocumentHistory { get; set; }
        public virtual ICollection<DocumentStatusReason> DocumentStatusReason { get; set; }
        public virtual ICollection<SentDocument> SentDocument { get; set; }
        public virtual ICollection<Document> Document { get; set; }
    }
}
