//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentProcedure : IEntity
    {
        public int DocumentId { get; set; }
        public int ProcedureId { get; set; }
        public int ProcedureStatusId { get; set; }
        public string Notes { get; set; }
    
        public virtual Procedure Procedure { get; set; }
        public virtual ProcedureStatus ProcedureStatus { get; set; }
        public virtual Document Document { get; set; }
    }
}
