//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentStatusReason : IEntity
    {
        public DocumentStatusReason()
        {
            this.SentDocument = new HashSet<SentDocument>();
        }
    
        public int Id { get; set; }
        public int DocumentStatusId { get; set; }
        public string Reason { get; set; }
        public bool Active { get; set; }
    
        public virtual DocumentStatus DocumentStatus { get; set; }
        public virtual ICollection<SentDocument> SentDocument { get; set; }
    }
}
