//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedure : IEntity
    {
        public Procedure()
        {
            this.DocumentProcedure = new HashSet<DocumentProcedure>();
            this.RequiredProcedure = new HashSet<RequiredProcedure>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<DocumentProcedure> DocumentProcedure { get; set; }
        public virtual ICollection<RequiredProcedure> RequiredProcedure { get; set; }
    }
}
