//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadOnlyType : IEntity
    {
        public ReadOnlyType()
        {
            this.ReadOnlyDepartment = new HashSet<ReadOnlyDepartment>();
            this.ReadOnlyUser = new HashSet<ReadOnlyUser>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ReadOnlyDepartment> ReadOnlyDepartment { get; set; }
        public virtual ICollection<ReadOnlyUser> ReadOnlyUser { get; set; }
    }
}
