//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadOnlyDepartment : IEntity
    {
        public int DocumentId { get; set; }
        public int DepartmentId { get; set; }
        public int ReadOnlyTypeId { get; set; }
    
        public virtual ReadOnlyType ReadOnlyType { get; set; }
        public virtual Document Document { get; set; }
        public virtual Department Department { get; set; }
    }
}
