//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedPerson : IEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int DoumentId { get; set; }
        public string NationalId { get; set; }
        public int NationalityId { get; set; }
    
        public virtual Nationality Nationality { get; set; }
        public virtual Document Document { get; set; }
    }
}
