//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentDocument : IEntity
    {
        public SentDocument()
        {
            this.RequiredProcedure = new HashSet<RequiredProcedure>();
        }
    
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public int FromUserId { get; set; }
        public int ToUserId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> DocumentStatusId { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public string Notes { get; set; }
        public bool Canceled { get; set; }
    
        public virtual DocumentStatus DocumentStatus { get; set; }
        public virtual DocumentStatusReason DocumentStatusReason { get; set; }
        public virtual ICollection<RequiredProcedure> RequiredProcedure { get; set; }
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
